### ISSUE TITLE
Can't pull on Windows Nano server?

### ISSUE THREAD

**Issue by Sean-Brown** [sixeyed/dockerfiles-windows#1]
I'm remoted into a nano server. I have downloaded other docker images on this PC, including the microsoft/nanoserver image. I try to pull the registry and I get the following error:

![image](https://cloud.githubusercontent.com/assets/1503131/23555419/e10ee3c0-fff6-11e6-8fac-1c88c6b01aaa.png)

**Comment by sixeyed** [comment]
Hi @Sean-Brown - there's no `latest` tag, so you need to `docker pull sixeyed/registry:nanoserver`. That error message isn't very helpful though. LMK if you can pull with the specific tag.

**Comment by Sean-Brown** [comment]
that worked, thank you!
